### ISSUE TITLE
Instructions only work when default is Python3

### ISSUE THREAD

**Issue by lczech** [phylo42/EPIK#8]
Hi again,

same as https://github.com/phylo42/IPK/issues/16, on systems on which Python2 is still the default, the command

    python epik.py --help

fails, while

    ./epik.py --help

works. I think that should be fixed in the documentation :-)

Cheers
Lucas

**Comment by nromashchenko** [comment]
Thanks, we updated the description. We, of course, enforce python3 in the shebang as we are in 2023 not 2003 :D. But you're right about default interpreters.

In README, I also hinted how to install EPIK so that users refer to the script easier. Installation of EPIK automatically closes this issue too.

Cheers!

**Comment by lczech** [comment]
Haha 

> We, of course, enforce python3 in the shebang as we are in 2023 not 2003 :D

Tell that to the folks that decided that Python 2.7 is still the default in Ubuntu 20.04... :-D

Thanks for fixing!
Lucas
